echo "We are trying this practical from linux EC2"
echo "We are from batch-33 and learning git/gihub"
echo "We are learning Branching"
echo "Devops is quite interesting"
echo "Now learning Github"
echo "Learning Jenkins and trying some scenarios"
echo "Learning Jenkins and trying some scenarios"
